FROM python:3.10-slim-buster

ENV API_BASE_URL = https://api.ryanwilk.com
WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./main.py /app/main.py

CMD ["python", "main.py"]
